version: "3.1"

services:
  frontend:
    image: akshaysachdeva1234/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "9000:5000"
    depends_on:
      - backend
  backend:
    image: akshaysachdeva1234/backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
  nginx:
    image: nginx:1.17
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - frontend
#      - backend
    volumes:
      - ./proxy-data-nginx/nginx:/etc/nginx/conf.d
      - ./proxy-data-nginx/certbot/conf:/etc/letsencrypt
      - ./proxy-data-nginx/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ./proxy-data-nginx/certbot/conf:/etc/letsencrypt
      - ./proxy-data-nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"