version: "3.1"

services:
  frontend:
    image: akshaysachdeva1234/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "9000:5000"
    depends_on:
      - backend
  backend:
    image: akshaysachdeva1234/backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
